import time, json, os, sys, copy
import gymnasium
from miniwob.action import ActionTypes, ActionSpaceConfig
from miniwob.reward import get_binary_reward
from miniwob.reward import get_thresholded_reward

import numpy as np
from html_tools import HtmlParser, basic_attrs
from miniwob_tools import ActionParser, testcases, mwpp_attrs, not_clickable_tag, miniwob_attrs
from miniwob_tools import save_pixel_array, get_dom_list, get_html, update_dom_list, get_position_bar, get_position_info, process_dom_list
from llms import CallLLM

import multiprocessing as mp

import logging, time, random, secrets
from pathlib import Path

import re

# # laj debug
# from miniwob_tools import testcases_laj

LOG_FOLDER = 'log_files'
Path(LOG_FOLDER).mkdir(parents=True, exist_ok=True)
LOG_ID = f"{time.strftime('%Y%m%d_%H%M%S', time.localtime())}_{random.randint(0, 10000)}"

LOG_FILE_NAME = f'{LOG_FOLDER}/log_{LOG_ID}.log'
LOG_CONTENT = f'{LOG_FOLDER}/result/'
Path(LOG_CONTENT).mkdir(parents=True, exist_ok=True)

logger = logging.getLogger('logger')
logger.setLevel(logging.INFO)

console_handler = logging.StreamHandler()
console_handler.setLevel(logging.DEBUG)
logger.addHandler(console_handler)

file_handler = logging.FileHandler(LOG_FILE_NAME)
file_handler.setLevel(logging.DEBUG)
logger.addHandler(file_handler)

# Set the log format
formatter = logging.Formatter("%(asctime)s - %(levelname)s - %(message)s")
console_handler.setFormatter(formatter)
file_handler.setFormatter(formatter)

import asyncio
class TestMiniwob:
    def __init__(self, model_path='chatgpt', result_path=LOG_CONTENT, cuda: str='0', log_path='logs/', prompt='new_action_space'):
        print("in TestMiniwob: __init__")
        self.action_parser = ActionParser(prompt=prompt)
        self.result_path = result_path
        self.llm = CallLLM(model_path, cuda)
        #laj debug
        self.pic_cnt = 0
    
    def get_operation(self, prompt: str):
        # Run the coroutine in the event loop
        res = asyncio.run(self.llm.model_call(prompt))  # go llms/call.py -> model_call
        logger.debug(f"LLM Response type: {type(res)}, value: {res}")
        print(f"LLM Response type: {type(res)}, value: {res}")
        act = self.action_parser.extract(res)
        return act, res  # back 107
    
    def policy(self, obs, env, prev_ops):      
        def get_position_by_bid(dom_list: list, bid: int) -> tuple:
            for elem in dom_list:
                if elem['ref'] == bid:
                    x = float(elem['left'] + elem['width'] * 0.5)
                    y = min(max(float(elem['top'] + elem['height'] * 0.5), 55.0), 200.0)
                    return np.array([x, y], dtype=float)
            return (0, 0)
        
        #save_pixel_array(obs.get('screenshot', ''), '1.png')
        # laj debug
        self.pic_cnt += 1
        #save_pixel_array(obs.get('screenshot', ''), f'./screenshot1129/{self.pic_cnt}.png')

        target = obs.get('utterance', '')

        print("----- New -----")
        
        dom_list = obs.get('dom_elements', [])
        print("dom_list: ", dom_list)
        action = env.unwrapped.create_action(ActionTypes.NONE)
        print("action: ", action)
        if len(dom_list) <= 0:
            return action, {}
        
        rhtml, obs_elem = get_html(copy.deepcopy(dom_list))
        print("rhtml", rhtml)
        print("obs_elem", obs_elem)
        
        args = {
            'use_position': False,
            'id_attr': 'ref',
            'label_attr': 'label',
            'label_generator': 'order',
            'attr_list': miniwob_attrs,
            'obs_elem': obs_elem,
            'prompt': 'refine',
        }
        hp = HtmlParser(rhtml, args)
        res = hp.parse_tree()
        print("res", res)
        html = res.get('html', '')
        print("html", html)
        
        ndom_list = update_dom_list(dom_list)
        
        # pos_bar = get_position_bar(ndom_list)
        # prev_str = '\n'.join(prev_ops[-10:]) if len(prev_ops) > 0 else 'None'
        # prompt = self.action_parser.get_prompt() % (html, pos_bar, prev_str, target)
        
        pos_bar = get_position_info(ndom_list)
        prev_str = '\n'.join(prev_ops) if len(prev_ops) > 0 else 'None'
        prompt = self.action_parser.get_prompt() % (html, prev_str, pos_bar, target)
        
        # TODO: For debug
        
        # for dom in ndom_list:
        #     bid = str(dom.get('ref', ''))
        #     label = hp.id_label_converter(bid)
        #     dom['label'] = label
        # print(rhtml)
        # print('\n'.join(get_dom_list(ndom_list)))
        print('\n[Prompt]', prompt)
        print('[End of Prompt]')
        
        act, res = self.get_operation(prompt)  # to 48
        
        cmsg = {
            'dom': process_dom_list(dom_list),
            'prompt': prompt,
            'response': res,
            'action': json.dumps(act, ensure_ascii=False),
        }
        
        print('[Action]', act)  # action generated by LLM
        print('[Response]', res)  # response from LLM  # laj-debug
        
        if act is None:
            return action, cmsg
        
        intent, op, param = act

        print("Intent: ", intent)
        print("Operation: ", op)
        print("Param: ", param)

        segment = 'None'
        
        if op in ['Click', 'Hover', 'Type', 'Select']:
            if param is None or len(param) == 0:
                return action, cmsg
            label = param[0]
            bid = hp.id_label_converter(label)
            if len(bid) == 0:
                return action, cmsg
            
            segment = hp.get_segment(bid)
            position = get_position_by_bid(dom_list, int(bid))

        print("Segment: ", segment)
        print("Position: ", position)
        
        # command_prompt = {
        #     'Click': '#Click# %s',
        #     'Hover': '#Hover# %s',
        #     'Scroll_up': '#Scroll_up#',
        #     'Scroll_down': '#Scroll_down#',
        #     'Type': '#Type# %s %s',
        # }
        
        # command_prompt = {
        #     'Click': "click('%s')",
        #     'Hover': "hover('%s')",
        #     'Scroll_up': "scroll_page('up')",
        #     'Scroll_down': "scroll_page('down')",
        #     'Type': "type_string('%s', '%s', %s)"
        # }

        command_prompt = {
            'Click': "click('%s')",
            'Hover': "hover('%s')",
            'Scroll_up': "scroll_page('up')",
            'Scroll_down': "scroll_page('down')",
            'Type': "type_string('%s', '%s', %s)",
            'Select': "select('%s', '%s')",
            # 'Go_forward': "go('forward')",
            # 'Go_backward': "go('backward')",
            # 'Jump_to': "jump_to('%s', %s)",
            # 'Switch_tab': "switch_tab(%d)",
            # 'User_input': "user_input('%s')",
            # 'Finish': "finish(%s)"
        }

        actions = []
        commands = []
        
        if op == 'Click':
            action = env.unwrapped.create_action(ActionTypes.CLICK_COORDS, coords=position)
            actions.append(action)
            command = command_prompt[op] % label
            commands.append(command)
        if op == 'Hover':
            action = env.unwrapped.create_action(ActionTypes.MOVE_COORDS, coords=position)
            actions.append(action)
            command = command_prompt[op] % label
            commands.append(command)
        if op == 'Scroll_up':
            action = env.unwrapped.create_action(ActionTypes.SCROLL_UP_COORDS, coords=(80, 80))
            actions.append(action)
            command = command_prompt[op]
            commands.append(command)
        if op == 'Scroll_down':
            action = env.unwrapped.create_action(ActionTypes.SCROLL_DOWN_COORDS, coords=(80, 80))
            actions.append(action)
            command = command_prompt[op]
            commands.append(command)
        if op == 'Type':
            clear_text = '\uE003' * 500
            enter_text = '\uE006' if param[2] else ''
            action = env.unwrapped.create_action(ActionTypes.FOCUS_ELEMENT_AND_TYPE_TEXT, ref=bid, text=clear_text+param[1]+enter_text)
            actions.append(action)
            command = command_prompt[op] % (label, param[1], param[2])
            commands.append(command)

        # laj debug
        if op == "Select":
            action = env.unwrapped.create_action(ActionTypes.CLICK_COORDS, coords=position)
            actions.append(action)
            command = command_prompt["Click"] % label
            commands.append(command)
            print("Action1: ", action)
            print("Command1:", command)

            # action = env.unwrapped.create_action(ActionTypes.CLICK_COORDS, coords=position)
            # actions.append(action)
            # command = command_prompt["Click"] % param[1]
            # commands.append(command)
            # print("Action2: ", action)
            # print("Command2:", command)


        # if op == 'Select':
        #     action = env.unwrapped.create_action(ActionTypes.SELECT_OPTION, ref=bid, option=param[1])  # None
        #     command = command_prompt[op] % (label, param[1])
        # if op == 'Go_forward':
        #     action = env.unwrapped.create_action(ActionTypes.NAVIGATE_FORWARD)  # None
        #     command = command_prompt[op]
        # if op == 'Go_backward':
        #     action = env.unwrapped.create_action(ActionTypes.NAVIGATE_BACKWARD)  #None
        #     command = command_prompt[op]
        # if op == 'Jump_to':
        #     action = env.unwrapped.create_action(ActionTypes.JUMP_TO_URL, url=param[0], new_tab=param[1])  # None
        #     command = command_prompt[op] % (param[0], param[1])
        # if op == 'Switch_tab':
        #     action = env.unwrapped.create_action(ActionTypes.SWITCH_TAB, tab_index=param[0]) # None
        #     command = command_prompt[op] % param[0]
        # if op == 'User_input':
        #     action = env.unwrapped.create_action(ActionTypes.WAIT_FOR_INPUT, message=param[0]) # None
        #     command = command_prompt[op] % param[0]
        # if op == 'Finish':
        #     action = env.unwrapped.create_action(ActionTypes.FINISH_TASK, answer=param[0] if param[0] else None) # None
        #     command = command_prompt[op] % (param[0] if param[0] else 'None')
        
        print("Command Prompt Action\n", actions)
        ix = len(prev_ops) + 1
        # cur_op = f'{ix}. Html segment: {segment}; Operation: {command};'
        cur_op = f'{commands} #HTML Segment: {segment}'  # current operation
        print("Current operation(Command): ", cur_op)

        prev_ops.append(cur_op)  # previous operations
        #return action, cmsg  # back 232: self.policy(obs, env, prev_ops)
        return actions,cmsg, html, res, target


    def cal_rewards(self, html, res_action, task_prompt):
        # laj debug

        print("-------------------- in cal_rewards -------------------")

        print("html", html)
        print("res_action", res_action)
        print("task_prompt", task_prompt)

        print("\n")

        action_patterns = {
            "Click": r'click\("([a-zA-Z]+)"\)',
            "Type": r"type_string\('([a-zA-Z]+)', '([a-zA-Z]+)', \"(True|False)\"\)"
        } # patterns in action

        action_type = ""
        for action, pattern in action_patterns.items():
            action_matches = re.findall(pattern, res_action)
            action_type = action
            if len(action_matches) > 0:
                break
        print("action_matches list",action_matches)
        action_matches = action_matches[0].strip()  # get the first element in the list
        print("action_matches", action_matches)
        print("action_type", action_type)

        if action_type == "Click":
            # click_html_patterns = [
            #     r'<button\[([^\]]+)\]\|\s*(.+?)>',
            #     r'<option\[([^\]]+)\]\|\s*(.+?)>',
            #     r'<select\[([^\]]+)\]\|\s*([a-zA-Z0-9])',
            #     r'<input\[([^\]]+)\]\|\s*([a-zA-Z0-9])',
            #
            # ]  # patterns in html
            #
            # click_html_matches = []
            # for pattern in click_html_patterns:
            #     click_html_matches.extend(re.findall(pattern, html))  # find all the click_id and text in the html, such as [('B', 'No')]
            #
            # # loop each tuple in the click_html_matches
            # for click_html_match in click_html_matches:
            #     click_id = click_html_match[0]
            #     click_text = click_html_match[1].strip()
            #     print("action_matches, click_id, click_text, task_prompt")
            #     print(action_matches, click_id, click_text, task_prompt)
            #     if action_matches in click_id or click_text in task_prompt:
            #         return 1.0

            click_html_patterns = [
                r'<(.+?)\[([^\]]+)\]\|\s*(.+?)>',
                r'<(.+?)\[([^\]]+)\]\|\s*([a-zA-Z0-9])',

            ]  # patterns in html

            click_html_matches = []
            for pattern in click_html_patterns:
                click_html_matches.extend(re.findall(pattern, html))

            for click_html_match in click_html_matches:
                click_tag = click_html_match[0]
                click_id = click_html_match[1]
                click_text = click_html_match[2].strip()
                print("action_matches, click_id, click_text, task_prompt")
                print(action_matches, ",", click_id, ",", click_text, ",", task_prompt)
                if action_matches in click_id or click_text in task_prompt:
                    return 1.0

        elif action_type == "Type":
            type_html_patterns = [
                r'<input\[([^\]]+)\]\|',
            ]

            type_html_matches = []
            for pattern in type_html_patterns:
                type_html_matches.extend(re.findall(pattern, html))  # find all the input id in the html, such as ['A']

            for type_html_match in type_html_matches:
                type_id = type_html_match
                print("type_id", type_id)
                if action_matches in type_id:
                    return 1.0

        else :
            return 0.0

        return 0.0

                
    def test(self, testname: str='', test_cnt: int=10) -> dict:
        asc = ActionSpaceConfig.get_preset()
        asc.scroll_amount = 145
        asc.scroll_time = 100
        # env = gymnasium.make(f'miniwob/{testname}-v1', reward_processor=get_binary_reward, action_space_config=asc)#, render_mode='human')
        # laj-debug
        # Define a threshold for binarizing the reward
        threshold = 0.05
        reward_processor = lambda reward: get_thresholded_reward(reward, threshold)

        env = gymnasium.make(f'miniwob/{testname}-v1', reward_processor=reward_processor, action_space_config=asc)
           
        rewards = []
        mission_history = []
        
        test_path = os.path.join(self.result_path, f'{testname}.json')
        if os.path.exists(test_path):
            with open(test_path, 'r') as f:
                data = json.load(f)
            completed = data.get('completed', 0)
            if completed >= test_cnt:             
                score = data.get('avg_score', 0)
                return { testname: score }
        
        # run test
        secrets_generator = secrets.SystemRandom()
        try:
            print("in run test")
            seed_id = secrets_generator.randint(0, 10**9)
            obs, info = env.reset(seed=seed_id)
            for ix in range(test_cnt):
                target = obs.get('utterance', '')
                meta = {
                    'seed': seed_id,
                    'task': testname,
                    'case_id': ix,
                }
                
                mission_path = os.path.join(self.result_path, f'{testname}_{ix}.json')
                if os.path.exists(mission_path):
                    with open(mission_path, 'r') as f:
                        data = json.load(f)
                    if 'result' in data:
                        result = data['result']
                        rewards.append(result)
                        continue
                
                terminated = False
                reward = 0
                prev_ops = []
                
                llm_histories = []

                print("before while loop")
                while True:
                    action, cmsg, html, res_action, task_prompt = self.policy(obs, env, prev_ops)  # to 55
                    # print(action)  # already printed in the policy function
                    if len(cmsg) > 0:
                        llm_histories.append(cmsg)

                    print("cmsg: ", cmsg)

                    for act in action:
                        obs, reward, terminated, truncated, info = env.step(act)
                        if reward != 1.0:
                            reward = self.cal_rewards(html, res_action, task_prompt)
                        print("reward", reward)
                        print("-------------------- out of cal_rewards -------------------")
                        print("reward, terminated, truncated, info")
                        print(reward, terminated, truncated, info)

                        print("obs")
                        print(obs)

                        time.sleep(0.3)
                    
                    if terminated or reward != 0:
                        seed_id = secrets_generator.randint(0, 10**9)
                        obs, info = env.reset(seed=seed_id)
                        break
                    
                    time.sleep(0.3)
                    obs, _, _, _, _ = env.step(env.unwrapped.create_action(ActionTypes.NONE))
                
                reward = 0 if reward < 0 else reward
                rewards.append(reward)   

                meta.update({
                    'result': reward,
                })
                 
                logger.info(json.dumps(meta, ensure_ascii=False))
                
                meta.update({
                    'log_id': LOG_ID,
                    'target': target,
                    'llm_histories': llm_histories
                })
                mission_history.append(meta)
                
                with open(mission_path, 'w') as f:
                    json.dump(meta, f, ensure_ascii=False)
        
        except Exception as e:
            logger.error(f"Error in test method: {str(e)}")
            logger.error(f"Error type: {type(e)}")
            import traceback
            logger.error(traceback.format_exc())
        finally:
            env.close()
        
        if len(rewards) == 0:
            rewards.append(0)
        
        score = np.mean(rewards)
        meta = {
            'task': testname,
            'avg_score': score,
            'completed': len(rewards),
        }
        
        logger.info(json.dumps(meta, ensure_ascii=False))
        
        meta.update({
            'log_id': LOG_ID,
        })
        
        with open(test_path, 'w') as f:
            json.dump(meta, f, ensure_ascii=False)
            
        return { testname: score }  # back to around303: def test_all_parallel

    def test_all_parallel(self, tasks: list=testcases, test_cnt: int=10):
        result, rewards = {}, []
        
        for testcase in tasks:
            ret = self.test(testcase, test_cnt)  # to 177
            result.update(ret)
            rewards.extend(ret.values())
            
        self.log_all_result(result, rewards)
        return result
        
    @staticmethod
    def log_all_result(result: dict, rewards: list):
        logger.info('------')
        for k, v in result.items():
            logger.info('{:<30} {:6.2f}'.format(k, v))
        
        logger.info('{:<30} {:6.3f}'.format('all', np.mean(rewards)))

def create_job(q, model_path: str, result_path: str, cuda: str, tasks: list[str], test_cnt: int=10):
    test = TestMiniwob(model_path, result_path, cuda)
    result = test.test_all_parallel(tasks, test_cnt)
    q.put(result)

if __name__ == '__main__':
    cudas = sys.argv[1]
    test_cnt = int(sys.argv[2])
    model_path = sys.argv[3] 
    result_path = sys.argv[4] 
    # model_path = '/workspace/hanyu/hanyu/ckpt/autoglm/sft/step2/chatglm-9300'
    # result_path = 'result-0/'
    
    if not os.path.exists(result_path):
        os.makedirs(result_path)
    
    if model_path == 'manual':
        test = TestMiniwob('manual', result_path)
        test.test_all_parallel(['enter-text'])
    
    else:
        cuda_ids = cudas.split(',')
        cudas_count = len(cuda_ids)
        
        result, rewards = {}, []
        
        tests = []

        # laj debug
        test_num = 0

        for testname in testcases:
            print("testname",testname)
            test_path = os.path.join(result_path, f'{testname}.json')
            if os.path.exists(test_path):
                with open(test_path, 'r') as f:
                    data = json.load(f)
                completed = data.get('completed', 0)
                if completed >= test_cnt:  
                    score = data.get('avg_score', 0)
                    result.update({ testname: score })
                    rewards.append(score)
                    continue
            tests.append(testname)

            # laj debug
            # test_num += 1
            # if test_num >= 10:
            #     break
        # print(tests)
        task_cnt = len(tests)
        print("task_cnt", task_cnt)
        batch = (task_cnt + cudas_count - 1) // cudas_count
        
        q = mp.Queue()
        processes = []
            
        for ix, cuda in enumerate(cuda_ids):
            p = mp.Process(target=create_job, args=(q, model_path, result_path, cuda, tests[ix * batch: (ix + 1) * batch], test_cnt, ))  # entrance: create_job
            p.start()
            processes.append(p)

        for p in processes:
            ret = q.get()
            result.update(ret)
            rewards.extend(ret.values())
            
        for p in processes:
            p.join()
        
        TestMiniwob.log_all_result(result, rewards)
